add aws-backup module
gravicore/terraform-gravicore-modules pull request #139
Opened 2021-07-10 01:36 UTC by syousry6

2021-07-13 00:44 UTC, TysonBeck commented on aws/aws-backup/aws_backup.tf
> +  name        = join("-", [local.module_prefix, "vault"])
- [ ] Add count attribute

2021-07-13 00:44 UTC, TysonBeck commented on aws/aws-backup/aws_backup.tf
> +  name = join("-", [local.module_prefix, "plan"])
- [ ] Add count attribute

2021-07-13 00:44 UTC, TysonBeck commented on aws/aws-backup/aws_backup.tf
> +  iam_role_arn = aws_iam_role.aws_backup_role.arn
- [ ] Add count attribute

2021-07-13 00:44 UTC, TysonBeck commented on aws/aws-backup/aws_backup.tf
> +  count                    = var.create ? 1 : 0
- [ ] Make count dynamic so kms key can be passed in

2021-07-13 00:44 UTC, TysonBeck commented on aws/aws-backup/aws_backup.tf
> +  rule {
- [ ] Create dynamic rule with map instead of predefined rules

2021-07-13 00:44 UTC, TysonBeck commented on aws/aws-backup/aws_backup.tf
> +variable "daily_cron" {
- [ ] Remove extra variables when modified for dynamic rule

2021-07-13 00:44 UTC, TysonBeck commented on aws/aws-backup/aws_backup.tf
> +
- [ ] Add variable for passing in KMS key arn

2021-07-20 15:00 UTC, jeremyodle requested changes
- [ ] Add `aws-backup` to .github Labeler
- [ ] Update README

2021-07-20 17:31 UTC, jeremyodle commented on aws/aws-backup/aws_backup.tf
> +  name          = "alias/${replace(local.stage_prefix, var.delimiter, "/")}/aws-backup"
- [ ] Use module name instead of hardcoding

2021-07-20 17:33 UTC, jeremyodle commented
- [ ] Remove Terraform Formatting comment from Terraform pipeline

2021-08-05 23:05 UTC, jeremyodle requested changes
- [ ] Rename module to `backup`

2021-08-05 23:10 UTC, jeremyodle approved these changes

2021-08-05 23:12 UTC, jeremyodle submitted a review, later dismissed

2021-08-05 23:19 UTC, jeremyodle approved these changes

2021-08-05 23:25 UTC, merged